---
- hosts: 192.168.121.133
  user: root
  become: true
  tasks:
  - name: Downloading the Tomcat
    get_url:
       url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.60/bin/apache-tomcat-8.5.60.tar.gz
       dest: /root/Downloads
